version: "3.9"

services:
  app:
    image: paozero-noname:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
      - "8080:8080"
    restart: unless-stopped
